version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzaSite
    networks:
      - pizza-site-network
  
  # nest-api:
  #   container_name: nest-api
  #   image: nest-api
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   networks:
  #     - pizza-site-network
networks:
  pizza-site-network: